### ISSUE TITLE
WebVR button can be difficult to see if the scene behind it does not provide enough contrast

### ISSUE THREAD

**Issue by brianpeiris** [borismus/webvr-boilerplate#13]
Maybe a black or white border around the icon and text would help.

**Comment by brianpeiris** [comment]
With #60, I was able to workaround this by darkening the button with filters (I have to use `!important` though):

``` css
.webvr-button {
  filter: brightness(0) !important;
  -webkit-filter: brightness(0) !important;
}
.webvr-button:hover {
  filter: drop-shadow(0 0 2px rgba(0,0,0,1)) !important;
  -webkit-filter: drop-shadow(0 0 2px rgba(0,0,0,1)) !important;
}
```
